apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-data
  namespace: bolblab-games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
